// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dbSilhouetteCpp
Rcpp::NumericVector dbSilhouetteCpp(Rcpp::NumericMatrix data, Rcpp::List postPartitionMCMC);
RcppExport SEXP _AnalisysLongData_dbSilhouetteCpp(SEXP dataSEXP, SEXP postPartitionMCMCSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type postPartitionMCMC(postPartitionMCMCSEXP);
    rcpp_result_gen = Rcpp::wrap(dbSilhouetteCpp(data, postPartitionMCMC));
    return rcpp_result_gen;
END_RCPP
}
// bridge_mcmcFunctionalData
Rcpp::List bridge_mcmcFunctionalData(Rcpp::NumericMatrix data, Rcpp::NumericMatrix baseMeasure, double r, Rcpp::NumericVector hyperWeights, Rcpp::NumericVector iterations, double p0, unsigned int lag, unsigned int n0);
RcppExport SEXP _AnalisysLongData_bridge_mcmcFunctionalData(SEXP dataSEXP, SEXP baseMeasureSEXP, SEXP rSEXP, SEXP hyperWeightsSEXP, SEXP iterationsSEXP, SEXP p0SEXP, SEXP lagSEXP, SEXP n0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type baseMeasure(baseMeasureSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hyperWeights(hyperWeightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n0(n0SEXP);
    rcpp_result_gen = Rcpp::wrap(bridge_mcmcFunctionalData(data, baseMeasure, r, hyperWeights, iterations, p0, lag, n0));
    return rcpp_result_gen;
END_RCPP
}
// bridge_mcmcFunctionalDataMissing
Rcpp::List bridge_mcmcFunctionalDataMissing(Rcpp::NumericMatrix data, Rcpp::NumericMatrix baseMeasure, double r, Rcpp::NumericVector hyperWeights, Rcpp::NumericVector iterations, double p0, unsigned int lag, unsigned int n0);
RcppExport SEXP _AnalisysLongData_bridge_mcmcFunctionalDataMissing(SEXP dataSEXP, SEXP baseMeasureSEXP, SEXP rSEXP, SEXP hyperWeightsSEXP, SEXP iterationsSEXP, SEXP p0SEXP, SEXP lagSEXP, SEXP n0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type baseMeasure(baseMeasureSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hyperWeights(hyperWeightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n0(n0SEXP);
    rcpp_result_gen = Rcpp::wrap(bridge_mcmcFunctionalDataMissing(data, baseMeasure, r, hyperWeights, iterations, p0, lag, n0));
    return rcpp_result_gen;
END_RCPP
}
// bridge_dbSilhouette
Rcpp::NumericVector bridge_dbSilhouette(Rcpp::NumericMatrix data, Rcpp::List postPartitionMCMC);
RcppExport SEXP _AnalisysLongData_bridge_dbSilhouette(SEXP dataSEXP, SEXP postPartitionMCMCSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type postPartitionMCMC(postPartitionMCMCSEXP);
    rcpp_result_gen = Rcpp::wrap(bridge_dbSilhouette(data, postPartitionMCMC));
    return rcpp_result_gen;
END_RCPP
}
// mcmcFunctionalDataCpp
Rcpp::List mcmcFunctionalDataCpp(Rcpp::NumericMatrix data, Rcpp::NumericMatrix baseMeasure, double r, Rcpp::NumericVector hyperWeights, Rcpp::NumericVector iterations, double p0, unsigned int lag, unsigned int n0);
RcppExport SEXP _AnalisysLongData_mcmcFunctionalDataCpp(SEXP dataSEXP, SEXP baseMeasureSEXP, SEXP rSEXP, SEXP hyperWeightsSEXP, SEXP iterationsSEXP, SEXP p0SEXP, SEXP lagSEXP, SEXP n0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type baseMeasure(baseMeasureSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hyperWeights(hyperWeightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n0(n0SEXP);
    rcpp_result_gen = Rcpp::wrap(mcmcFunctionalDataCpp(data, baseMeasure, r, hyperWeights, iterations, p0, lag, n0));
    return rcpp_result_gen;
END_RCPP
}
// mcmcFunctionalDataMissingCpp
Rcpp::List mcmcFunctionalDataMissingCpp(Rcpp::NumericMatrix data, Rcpp::NumericMatrix baseMeasure, double r, Rcpp::NumericVector hyperWeights, Rcpp::NumericVector iterations, double p0, unsigned int lag, unsigned int n0);
RcppExport SEXP _AnalisysLongData_mcmcFunctionalDataMissingCpp(SEXP dataSEXP, SEXP baseMeasureSEXP, SEXP rSEXP, SEXP hyperWeightsSEXP, SEXP iterationsSEXP, SEXP p0SEXP, SEXP lagSEXP, SEXP n0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type baseMeasure(baseMeasureSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hyperWeights(hyperWeightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n0(n0SEXP);
    rcpp_result_gen = Rcpp::wrap(mcmcFunctionalDataMissingCpp(data, baseMeasure, r, hyperWeights, iterations, p0, lag, n0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AnalisysLongData_dbSilhouetteCpp", (DL_FUNC) &_AnalisysLongData_dbSilhouetteCpp, 2},
    {"_AnalisysLongData_bridge_mcmcFunctionalData", (DL_FUNC) &_AnalisysLongData_bridge_mcmcFunctionalData, 8},
    {"_AnalisysLongData_bridge_mcmcFunctionalDataMissing", (DL_FUNC) &_AnalisysLongData_bridge_mcmcFunctionalDataMissing, 8},
    {"_AnalisysLongData_bridge_dbSilhouette", (DL_FUNC) &_AnalisysLongData_bridge_dbSilhouette, 2},
    {"_AnalisysLongData_mcmcFunctionalDataCpp", (DL_FUNC) &_AnalisysLongData_mcmcFunctionalDataCpp, 8},
    {"_AnalisysLongData_mcmcFunctionalDataMissingCpp", (DL_FUNC) &_AnalisysLongData_mcmcFunctionalDataMissingCpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_AnalisysLongData(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
