# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dbSilhouetteCpp <- function(data, postPartitionMCMC) {
    .Call('_AnalisysLongData_dbSilhouetteCpp', PACKAGE = 'AnalisysLongData', data, postPartitionMCMC)
}

bridge_mcmcFunctionalData <- function(data, baseMeasure, r, hyperWeights, iterations, p0 = 0.5, lag = 1L, n0 = 10L) {
    .Call('_AnalisysLongData_bridge_mcmcFunctionalData', PACKAGE = 'AnalisysLongData', data, baseMeasure, r, hyperWeights, iterations, p0, lag, n0)
}

bridge_mcmcFunctionalDataMissing <- function(data, baseMeasure, r, hyperWeights, iterations, p0 = 0.5, lag = 1L, n0 = 10L) {
    .Call('_AnalisysLongData_bridge_mcmcFunctionalDataMissing', PACKAGE = 'AnalisysLongData', data, baseMeasure, r, hyperWeights, iterations, p0, lag, n0)
}

bridge_dbSilhouette <- function(data, postPartitionMCMC) {
    .Call('_AnalisysLongData_bridge_dbSilhouette', PACKAGE = 'AnalisysLongData', data, postPartitionMCMC)
}

mcmcFunctionalDataCpp <- function(data, baseMeasure, r, hyperWeights, iterations, p0 = 0.5, lag = 1L, n0 = 10L) {
    .Call('_AnalisysLongData_mcmcFunctionalDataCpp', PACKAGE = 'AnalisysLongData', data, baseMeasure, r, hyperWeights, iterations, p0, lag, n0)
}

mcmcFunctionalDataMissingCpp <- function(data, baseMeasure, r, hyperWeights, iterations, p0 = 0.5, lag = 1L, n0 = 10L) {
    .Call('_AnalisysLongData_mcmcFunctionalDataMissingCpp', PACKAGE = 'AnalisysLongData', data, baseMeasure, r, hyperWeights, iterations, p0, lag, n0)
}

